# Generated by Django 5.2.17 on 2026-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
